### ISSUE TITLE
DLP-RF430CL WITH TIVA C

### ISSUE THREAD

**Issue by medsimo** [spirilis/RF430CL#1]
hello Spirilis !! 
how can I send (double, float, analog_pin) data to nfc ?
help please !! urgent.

**Comment by medsimo** [comment]
any help please ?
can someone helps me. ?

**Comment by spirilis** [comment]
Not sure what to do here.  Depends on what your cellphone side supports?  (assuming this is a cellphone you're using as the master)

**Comment by medsimo** [comment]
Yes i use my cellphone as master, what I need to do is introduced variables in NDEF_TXT . Something like (float to string) !!!

**Comment by medsimo** [comment]
Please see this link ... http://forum.43oh.com/topic/6441-energia-library-rf430cl-ti-nfc-rf430cl330h-library/#comment-76863

**Comment by spirilis** [comment]
I got it; see my reply over at 43oh :)

**Comment by medsimo** [comment]
hello friend !! How about SPI mode ? I need connecting the RF430bp to my aplication with SPI mode because I have "conflicting pin" when i use I2C mode. 

any help ?

**Comment by spirilis** [comment]
I don't have any SPI mode hardware to play with, so I couldn't test it.  I2C only for this library.
